<a href="https://colab.research.google.com/github/pandey-virat/Customer_Behaviour_Analysis/blob/main/customer_behaviour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("data_one.csv")
print(df.head(10))

   Unnamed: 0  Customer ID  Age Gender Item Purchased     Category  \
0           0            1   55   Male         Blouse     Clothing
1           1            2   19   Male        Sweater     Clothing
2           2            3   50   Male          Jeans     Clothing
3           3            4   21   Male        Sandals     Footwear
4           4            5   45   Male         Blouse     Clothing
5           5            6   46   Male       Sneakers     Footwear
6           6            7   63   Male          Shirt     Clothing
7           7            8   27   Male         Shorts     Clothing
8           8            9   26   Male           Coat    Outerwear
9           9           10   57   Male        Handbag  Accessories

   Purchase Amount (USD)       Location      Color  Season  Review Rating  \
0                     53       Kentucky       Gray  Winter            3.1
1                     64          Maine     Maroon  Winter            3.1
2                     73  Massachusetts     Maroon  Spring            3.1
3                     90   Rhode Island     Maroon  Spring            3.5
4                     49         Oregon  Turquoise  Spring            2.7
5                     20        Wyoming      White  Summer            2.9
6                     85        Montana       Gray    Fall            3.2
7                     34      Louisiana   Charcoal  Winter            3.2
8                     97  West Virginia     Silver  Summer            2.6
9                     31       Missouri       Pink  Spring            4.8

  Subscription Status   Shipping Type Discount Applied Promo Code Used  \
0                 Yes         Express              Yes             Yes
1                 Yes         Express              Yes             Yes
2                 Yes   Free Shipping              Yes             Yes
3                 Yes    Next Day Air              Yes             Yes
4                 Yes   Free Shipping              Yes             Yes
5                 Yes        Standard              Yes             Yes
6                 Yes   Free Shipping              Yes             Yes
7                 Yes   Free Shipping              Yes             Yes
8                 Yes         Express              Yes             Yes
9                 Yes  2-Day Shipping              Yes             Yes

   Previous Purchases Payment Method Frequency of Purchases
0                  14          Venmo            Fortnightly
1                   2           Cash            Fortnightly
2                  23    Credit Card                 Weekly
3                  49         PayPal                 Weekly
4                  31         PayPal               Annually
5                  14          Venmo                 Weekly
6                  49           Cash              Quarterly
7                  19    Credit Card                 Weekly
8                   8          Venmo               Annually
9                   4           Cash              Quarterly

In [ ]:
df.describe()

,Unnamed: 0,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1949.500000,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,1125.977353,15.207589,23.685392,0.716223,14.447125
min,0.000000,1.000000,18.000000,20.000000,2.500000,1.000000
25%,974.750000,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1949.500000,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2924.250000,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3899.000000,3900.000000,70.000000,100.000000,5.000000,50.000000

In [ ]:
df.isnull().sum()

Unnamed: 0                0
Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("purchase_amount_(usd)", "purchase_amount")
print(df.head(10))
#

   unnamed:_0  customer_id  age gender item_purchased     category  \
0           0            1   55   Male         Blouse     Clothing
1           1            2   19   Male        Sweater     Clothing
2           2            3   50   Male          Jeans     Clothing
3           3            4   21   Male        Sandals     Footwear
4           4            5   45   Male         Blouse     Clothing
5           5            6   46   Male       Sneakers     Footwear
6           6            7   63   Male          Shirt     Clothing
7           7            8   27   Male         Shorts     Clothing
8           8            9   26   Male           Coat    Outerwear
9           9           10   57   Male        Handbag  Accessories

   purchase_amount       location      color  season  review_rating  \
0               53       Kentucky       Gray  Winter            3.1
1               64          Maine     Maroon  Winter            3.1
2               73  Massachusetts     Maroon  Spring            3.1
3               90   Rhode Island     Maroon  Spring            3.5
4               49         Oregon  Turquoise  Spring            2.7
5               20        Wyoming      White  Summer            2.9
6               85        Montana       Gray    Fall            3.2
7               34      Louisiana   Charcoal  Winter            3.2
8               97  West Virginia     Silver  Summer            2.6
9               31       Missouri       Pink  Spring            4.8

  subscription_status   shipping_type discount_applied promo_code_used  \
0                 Yes         Express              Yes             Yes
1                 Yes         Express              Yes             Yes
2                 Yes   Free Shipping              Yes             Yes
3                 Yes    Next Day Air              Yes             Yes
4                 Yes   Free Shipping              Yes             Yes
5                 Yes        Standard              Yes             Yes
6                 Yes   Free Shipping              Yes             Yes
7                 Yes   Free Shipping              Yes             Yes
8                 Yes         Express              Yes             Yes
9                 Yes  2-Day Shipping              Yes             Yes

   previous_purchases payment_method frequency_of_purchases
0                  14          Venmo            Fortnightly
1                   2           Cash            Fortnightly
2                  23    Credit Card                 Weekly
3                  49         PayPal                 Weekly
4                  31         PayPal               Annually
5                  14          Venmo                 Weekly
6                  49           Cash              Quarterly
7                  19    Credit Card                 Weekly
8                   8          Venmo               Annually
9                   4           Cash              Quarterly

In [ ]:
df.columns

Index(['unnamed:_0', 'customer_id', 'age', 'gender', 'item_purchased',
       'category', 'purchase_amount', 'location', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
#creating a column for age group
labels = ["young","adult","middle-aged","senior"]
df["age_group"] = pd.qcut(df["age"],q=4,labels=labels)
#print only age and age group
print(df[["age","age_group"]])

      age    age_group
0      55  middle-aged
1      19        young
2      50  middle-aged
3      21        young
4      45  middle-aged
...   ...          ...
3895   40        adult
3896   52  middle-aged
3897   46  middle-aged
3898   44        adult
3899   52  middle-aged

[3900 rows x 2 columns]

In [ ]:
from numpy import frexp
# creating a column purchase_frequency_days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Annually' : 365,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Every 3 Months': 90
}
df["purchase_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)
print(df[['purchase_frequency_days','frequency_of_purchases']].head(10))

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [ ]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [ ]:
df = df.drop('promo_code_used', axis=1)

In [ ]:
df.columns

Index(['unnamed:_0', 'customer_id', 'age', 'gender', 'item_purchased',
       'category', 'purchase_amount', 'location', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [ ]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.45)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)